name: Node CI

on: []

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm pack
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: '*.tgz'
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
  download:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: npm install
      - run: env
      - run: npm list -g --depth=0
      - run: npm list --depth=0
      - run: node --version
      - run: node info.js # since artifacts are uploaded after a job has completed.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
