name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm pack
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: '*.tgz'
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
