on:
  workflow_dispatch:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -x
          touch a
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout -b pr
          git add a
          git commit -m "a"
          git push -u origin pr
          gh pr create -t test -b aaaa
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
