on:
  workflow_dispatch:
    inputs:
      title:
        description: "Release title"
        default: ""
        required: false
      dryrun:
        type: boolean
        description: Is dryrun?
        default: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: machine echo github
        env: { CONTENT: "${{ toJson(github) }}" }
        run: "echo $CONTENT"
